### ISSUE TITLE
CrashLoopBackOff Cloudflare-proxy-dns

### ISSUE THREAD

**Issue by AusomeOllie10** [ivanmorenoj/k3s-pihole-wireguard#1]
Hi, 

Below issue when running; all other containers fine, below is the error.

root@raspberrypi:/home/pi/k3s-pihole-wireguard/k8s# kubectl logs pihole-c79c75bd7-jw6n6 cloudflare-proxy-dns
standard_init_linux.go:228: exec user process caused: exec format error

Getting the above error with the Cloudflared DNS portion.

**Comment by ivanmorenoj** [comment]
It seems that the docker image for cloudflared is not available for arm.
